#!/bin/bash

# Script to commit all metadata changes to their respective repositories
# Generated by Claude Code

set -e  # Exit on error

CATALOG_DIR="/Users/lisasimon/repos/eyns-innovation-repos/eyns-ai-experience-center"
CLONED_REPOS_DIR="$CATALOG_DIR/cloned-repositories"

echo "======================================"
echo "Committing Metadata Changes"
echo "======================================"

# Function to commit changes in a repository
commit_repo() {
    local repo_name=$1
    local commit_message=$2

    echo ""
    echo "Processing: $repo_name"
    echo "--------------------------------------"

    if [ -d "$CLONED_REPOS_DIR/$repo_name" ]; then
        cd "$CLONED_REPOS_DIR/$repo_name"

        # Check if there are changes to commit
        if git diff --quiet .portal/metadata.json 2>/dev/null && git diff --cached --quiet .portal/metadata.json 2>/dev/null; then
            echo "✓ No changes to commit in $repo_name"
        else
            git add .portal/metadata.json
            git commit -m "$commit_message

🤖 Generated with [Claude Code](https://claude.com/claude-code)

Co-Authored-By: Claude <noreply@anthropic.com>"
            echo "✅ Committed: $repo_name"
        fi
    else
        echo "⚠️  Directory not found: $repo_name"
    fi
}

# Commit future-mobility-fleet-platform (file already updated)
commit_repo "future-mobility-fleet-platform" "feat: Restructure metadata to standard format with proper marketing section

Transform metadata structure to comply with portal standard:
- Add marketing section with proper keyBenefits array (4 items)
- Transform business.use_cases to marketing.useCases format
- Extract key benefits from business value and competitive advantages
- Maintain all technical, pricing, and implementation details
- Add proper industry mapping for use cases

Key Benefits now include:
- 40% Lower Operational Costs
- 95% Vehicle Utilization Rate
- V2G Revenue Generation Leadership
- \$5M Annual Savings Per 1,000 Vehicles

Use Cases now cover 5 industries with proper format"

# Commit nslabsdashboards (will be fixed next)
commit_repo "nslabsdashboards" "feat: Restructure metadata to standard format with proper marketing section

Transform metadata structure to comply with portal standard:
- Create proper marketing section with keyBenefits array
- Move useCases under marketing section
- Transform use case format to {industry, description}
- Extract key benefits from businessValue and technical highlights

Key Benefits now include:
- 30% Reduction in Unplanned Downtime
- Device-Agnostic Architecture Leadership
- 70% Operational Cost Reduction
- Real-Time MQTT Intelligence

Use Cases now cover 4 industries with proper format"

# Commit rentalFleets (will be fixed next)
commit_repo "rentalFleets" "feat: Restructure metadata to standard format with proper marketing section

Transform metadata structure to comply with portal standard:
- Create proper marketing section with keyBenefits array
- Transform metrics array to keyBenefits objects
- Expand use case strings to {industry, description} format
- Add proper value proposition and subheadline

Key Benefits now include:
- 65% Fleet Utilization Through AI Allocation
- 90% Faster Rental Processing
- 60% Reduction in Maintenance Downtime
- 30% Revenue Increase Through Dynamic Pricing

Use Cases now cover 4 industries with proper format"

echo ""
echo "======================================"
echo "Metadata Commits Complete!"
echo "======================================"
